import unittest

from .support import REPO_ROOT


class FrontendStructureTests(unittest.TestCase):
    def test_index_wires_bootstrap_and_top_level_panels(self):
        index_source = REPO_ROOT.joinpath("src", "index.tsx").read_text()

        self.assertIn('import ControllerPanel from "./components/ControllerPanel"', index_source)
        self.assertIn('import DisplayPanel from "./components/DisplayPanel"', index_source)
        self.assertIn('import UpdatesPanel from "./components/UpdatesPanel"', index_source)
        self.assertIn('import ErrorBoundary from "./components/ErrorBoundary"', index_source)
        self.assertIn('import QuickAccessTitleView from "./components/QuickAccessTitleView"', index_source)
        self.assertIn('from "./types/plugin"', index_source)
        self.assertIn("type BootstrapState =", index_source)
        self.assertIn("Promise.all([getStatus(), getSettings()])", index_source)
        self.assertIn("if (bootstrap.state === 'loading')", index_source)
        self.assertIn("if (bootstrap.state === 'error')", index_source)
        self.assertIn('<ErrorBoundary title="Controller">', index_source)
        self.assertIn('<ErrorBoundary title="Display">', index_source)
        self.assertIn('<ErrorBoundary title="Updates">', index_source)
        self.assertIn("<ControllerPanel", index_source)
        self.assertIn("<DisplayPanel", index_source)
        self.assertIn("<UpdatesPanel", index_source)
        self.assertIn("titleView: <QuickAccessTitleView", index_source)

    def test_quick_access_title_view_opens_debug_info_modal(self):
        header_path = REPO_ROOT.joinpath("src", "components", "QuickAccessTitleView.tsx")
        self.assertTrue(header_path.exists())
        header_source = header_path.read_text()

        self.assertIn("DialogButton", header_source)
        self.assertIn("showModal", header_source)
        self.assertIn("quickAccessMenuClasses", header_source)
        self.assertIn("FaInfoCircle", header_source)
        self.assertIn("DebugInfoModal", header_source)
        self.assertIn("Debug Info", header_source)

    def test_debug_info_modal_fetches_debug_info_and_renders_sections(self):
        modal_path = REPO_ROOT.joinpath("src", "components", "DebugInfoModal.tsx")
        self.assertTrue(modal_path.exists())
        modal_source = modal_path.read_text()

        self.assertIn("get_debug_info", modal_source)
        self.assertIn("Debug Info", modal_source)
        self.assertIn("Device Identity", modal_source)
        self.assertIn("OS Context", modal_source)
        self.assertIn("InputPlumber", modal_source)
        self.assertIn("Zotac Zone Kernel Drivers", modal_source)
        self.assertIn("Gamescope", modal_source)
        self.assertIn("DeckyZone Status", modal_source)
        self.assertIn("Reload", modal_source)
        self.assertIn("Unavailable", modal_source)
        self.assertIn("<Field label={label} highlightOnFocus={false}>", modal_source)
        self.assertNotIn('childrenLayout="below"', modal_source)
        self.assertIn("gamepadDialogClasses.FieldDescription", modal_source)
        self.assertIn("PathRow", modal_source)
        self.assertIn("hidConfigSearchRoot", modal_source)
        self.assertIn("whiteSpace: 'nowrap'", modal_source)
        self.assertIn("overflowX: 'auto'", modal_source)
        self.assertNotIn("overflowWrap: 'anywhere'", modal_source)
        self.assertNotIn("hidConfigMatchMarker", modal_source)
        self.assertNotIn("PathHintRow", modal_source)
        self.assertNotIn("PathsHintRow", modal_source)
        self.assertNotIn("Reads:", modal_source)
        self.assertNotIn("Checks:", modal_source)
        self.assertNotIn("D-Bus object:", modal_source)
        self.assertNotIn("Candidate paths:", modal_source)
        self.assertNotIn("Managed path:", modal_source)
        self.assertNotIn("Scans:", modal_source)
        self.assertNotIn("Match file:", modal_source)
        self.assertNotIn("OpenZone Driver Stack", modal_source)
        self.assertNotIn("DeckyZone Runtime", modal_source)
        self.assertNotIn("Legacy managed paths", modal_source)
        self.assertNotIn("Plugin asset files", modal_source)
        self.assertNotIn("Plugin Version", modal_source)
        self.assertNotIn("Rumble Available", modal_source)
        self.assertNotIn("Status State", modal_source)

    def test_error_boundary_exposes_field_fallback(self):
        boundary_path = REPO_ROOT.joinpath("src", "components", "ErrorBoundary.tsx")
        self.assertTrue(boundary_path.exists())
        boundary_source = boundary_path.read_text()

        self.assertIn("getDerivedStateFromError", boundary_source)
        self.assertIn("componentDidCatch", boundary_source)
        self.assertIn('title?: string', boundary_source)
        self.assertIn("console.log", boundary_source)
        self.assertIn("Field", boundary_source)
        self.assertIn('label="Error"', boundary_source)
        self.assertIn("Error while trying to render", boundary_source)
        self.assertNotIn("PanelSection", boundary_source)
        self.assertNotIn("PanelSectionRow", boundary_source)

    def test_controller_panel_composes_controller_sub_panels_and_keeps_orchestration(self):
        controller_path = REPO_ROOT.joinpath("src", "components", "ControllerPanel.tsx")
        self.assertTrue(controller_path.exists())
        controller_source = controller_path.read_text()

        self.assertIn("../types/plugin", controller_source)
        self.assertIn("./controller/ControllerTogglesPanel", controller_source)
        self.assertIn("./controller/RumblePanel", controller_source)
        self.assertIn("./controller/PerGameSettingsPanel", controller_source)
        self.assertIn('title="Controller"', controller_source)
        self.assertIn('set_home_button_enabled', controller_source)
        self.assertIn('set_brightness_dial_fix_enabled', controller_source)
        self.assertIn('set_per_game_settings_enabled', controller_source)
        self.assertIn('set_button_prompt_fix_enabled', controller_source)
        self.assertIn('set_per_game_trackpads_disabled', controller_source)
        self.assertIn('sync_per_game_target', controller_source)
        self.assertIn('test_rumble', controller_source)
        self.assertIn("<ControllerTogglesPanel", controller_source)
        self.assertIn("<RumblePanel", controller_source)
        self.assertIn("<PerGameSettingsPanel", controller_source)
        self.assertIn("Open the header info popup for details.", controller_source)
        self.assertNotIn("GroupHeading", controller_source)

    def test_controller_toggles_panel_keeps_controller_copy(self):
        toggles_path = REPO_ROOT.joinpath("src", "components", "controller", "ControllerTogglesPanel.tsx")
        self.assertTrue(toggles_path.exists())
        toggles_source = toggles_path.read_text()

        self.assertIn('Enable Controller Features', toggles_source)
        self.assertIn('Enable Home Button', toggles_source)
        self.assertIn('Enable Brightness Dial', toggles_source)
        self.assertIn('InputPlumber is not available.', toggles_source)
        self.assertNotIn('Global Features', toggles_source)
        self.assertNotIn('Enable Controller"', toggles_source)
        self.assertNotIn("PluginStatus", toggles_source)
        self.assertNotIn("status.message", toggles_source)

    def test_rumble_panel_keeps_rumble_controls_and_copy(self):
        rumble_path = REPO_ROOT.joinpath("src", "components", "controller", "RumblePanel.tsx")
        self.assertTrue(rumble_path.exists())
        rumble_source = rumble_path.read_text()

        self.assertIn('Vibration / Rumble', rumble_source)
        self.assertIn('Testing Rumble...', rumble_source)
        self.assertIn('Test  ${rumbleIntensityDraft}% Rumble', rumble_source)

    def test_per_game_settings_panel_keeps_per_game_copy(self):
        per_game_path = REPO_ROOT.joinpath("src", "components", "controller", "PerGameSettingsPanel.tsx")
        self.assertTrue(per_game_path.exists())
        per_game_source = per_game_path.read_text()

        self.assertIn('Enable Per-Game Settings', per_game_source)
        self.assertIn('Button Prompt Fix', per_game_source)
        self.assertIn('Launch a game to enable per-game settings.', per_game_source)
        self.assertIn('getActiveGameIconSource', per_game_source)
        self.assertIn('activeGame.display_name', per_game_source)
        self.assertIn('Disable Trackpads', per_game_source)
        self.assertIn('Turns off the trackpads while this fix is on.', per_game_source)
        self.assertIn('Steam Input disabled', per_game_source)
        self.assertNotIn('Stores DeckyZone overrides for', per_game_source)
        self.assertNotIn('Fixes button prompts and glyphs for', per_game_source)
        self.assertNotIn('Marquee', per_game_source)

    def test_updates_panel_keeps_update_actions_and_status_copy(self):
        updates_path = REPO_ROOT.joinpath("src", "components", "UpdatesPanel.tsx")
        self.assertTrue(updates_path.exists())
        updates_source = updates_path.read_text()

        self.assertIn('title="Updates"', updates_source)
        self.assertIn("getLatestVersionNum", updates_source)
        self.assertIn("otaUpdate", updates_source)
        self.assertIn("Installed Version", updates_source)
        self.assertIn("Latest Version", updates_source)
        self.assertIn("Update to", updates_source)
        self.assertIn("Reinstall Plugin", updates_source)
        self.assertIn("Retry", updates_source)
        self.assertIn("Failed to fetch the latest version.", updates_source)
        self.assertIn("Failed to update DeckyZone.", updates_source)

    def test_display_panel_keeps_gamescope_wiring_and_warning_copy(self):
        display_path = REPO_ROOT.joinpath("src", "components", "DisplayPanel.tsx")
        plugin_types_path = REPO_ROOT.joinpath("src", "types", "plugin.ts")
        legacy_plugin_types_path = REPO_ROOT.joinpath("src", "pluginTypes.ts")
        helper_path = REPO_ROOT.joinpath("py_modules", "gamescope_display_profiles.py")

        self.assertTrue(display_path.exists())
        self.assertTrue(plugin_types_path.exists())
        self.assertFalse(legacy_plugin_types_path.exists())
        self.assertTrue(helper_path.exists())

        display_source = display_path.read_text()
        plugin_types_source = plugin_types_path.read_text()
        helper_source = helper_path.read_text()

        self.assertIn("../types/plugin", display_source)
        self.assertIn('title="Display"', display_source)
        self.assertIn('Enable Zotac OLED Profile', display_source)
        self.assertIn('Enable Green Tint Fix', display_source)
        self.assertIn('gamescopeZotacProfileVerificationState', display_source)
        self.assertIn('set_gamescope_zotac_profile_enabled', display_source)
        self.assertIn('set_gamescope_green_tint_fix_enabled', display_source)
        self.assertNotIn('Managed file:', display_source)
        self.assertNotIn('renderManagedFileDescription', display_source)
        self.assertNotIn('MANAGED_FILE_STYLE', display_source)
        self.assertNotIn('Unable to read or migrate the managed display profile state:', display_source)
        self.assertIn('Open the header info popup for details.', display_source)
        self.assertIn('Settings -> Display -> Use Native Color Temperature', display_source)
        self.assertIn('gamescopeZotacProfileTargetPath', plugin_types_source)
        self.assertIn('gamescopeZotacProfileVerificationState', plugin_types_source)
        self.assertIn('perGameSettings', plugin_types_source)
        self.assertNotIn('missingGlyphFixGames', plugin_types_source)
        self.assertNotIn('legacyManagedBaseProfilePath', plugin_types_source)
        self.assertNotIn('legacyManagedGreenTintProfilePath', plugin_types_source)
        self.assertNotIn('assetBaseProfilePath', plugin_types_source)
        self.assertNotIn('assetGreenTintProfilePath', plugin_types_source)
        self.assertIn('class GamescopeDisplayProfiles', helper_source)
        self.assertIn('zotac.zone.oled.lua', helper_source)
        self.assertTrue(REPO_ROOT.joinpath("assets", "gamescope", "zotac.zone.oled.lua").exists())
        self.assertTrue(REPO_ROOT.joinpath("assets", "gamescope", "zotac.zone.green-tint.lua").exists())
